# 1
基本变量类型（命名、顺序、等距、等比）（离散、连续）
（1）nominal称名：性别，职位，地区，水果，血型，宗教信仰，学院名，省份，品牌，颜色，班级（123班），学科，国家，品种，门牌号，菜名，姓名
（2）ordinay顺序：排名，老中青年，成绩（ABCD，优良中差），肿瘤分期，衣服鞋尺码，辣度，职称，产品质量等级，饮料大中小杯，一二三线城市，英语考试分级，社会经济地位，景区评级
（3）interval等距：摄氏温标，海拔，经度，公元纪年，净收入，势能
（4）ratio等比：长度（身高），面积，速度，重量，体积，反应时间，开氏温标，年龄

离散：条形图bar
连续：直方图hist

基本统计量的计算和性质（均值、中位数、众数、全距、标准差、四分位距，标准化）
# 需要知道基本的英文名词 mean median mode range ……
mean
median
as.numeric(names(table(x)))[table(x) == max(table(x))]

构念、操作性定义

统计量（statistic）是针对样本数据（sample）
参数（parameter）是针对总体数据（population）

正/负偏态

# 2
基本概率运算（加法、乘法、贝叶斯公式）
概率质量函数PMF
标准化和z分数

# 3
PDF，CDF
中心极限定理
z分数和标准化

# 4
假设检验原理（虚无假设和备选假设，第I、II类错误，效力power，p值）
z检验的步骤：虚无假设，显著性水平，计算z值，得到结论（并计算p值，效应量）


考试时间：11.6 8点-10点
考试形式：机房作答后上传文件
考试范围：直到10.29号课上讲的内容
# 两个班或许昨天的讲课进度不太一致
假设检验一定是重点
z/t检验的重要性：假设检验入门，下半学期的内容基本都围绕假设检验展开
考试难度：不会全部考作业原题，但知识点不会有大的变动。考试均分当然会低于作业（毕竟有时间限制+不完全开卷）
重要的是相对排名
题型：不定项选择题*10（40分），大题数量不确定（毕竟60分，4-5个左右吧）
暂定，也可能改为8个选择

# 复习时间：1-2天（在平时认真完成作业的基础上）
# 复习内容：PPT、作业题和答案、老师给的代码、书
# 可以带一页单页的A4纸（打印or手写均可），但不能超过一页

选择题：概念理解。PPT的每一句话，专业术语和定义如果自己无法复述（“解释一下**的含义”），可以写在cheating sheet上
大题：方法不要出错（不过现在也没啥方法hhh），不要粗心算错，基本扣分不会太多

# 一定要自己做cheating sheet（复习的过程）
# 怎么做cheating sheet
边复习边加，写上关键词（字数有限），写上自己不太会的，写上曾经做错的，写上觉得会考的
# 看一个例子（仅供参考）

# 考试操作练习（解除控屏）
解压R包
发送文件
提交文件


